(define (problem strips-gripper-x-2)
   (:domain gripper-strips)
   (:objects rooma roomb ball6 ball5 ball4 ball3 ball2 ball1 left right - object)
   (:init (room rooma)
          (room roomb)
          (ball ball6)
          (ball ball5)
          (ball ball4)
          (ball ball3)
          (ball ball2)
          (ball ball1)
          (at-robby rooma)
          (free left)
          (free right)
          (in ball6 rooma)
          (in ball5 rooma)
          (in ball4 rooma)
          (in ball3 rooma)
          (in ball2 rooma)
          (in ball1 rooma)
          (gripper left)
          (gripper right))
   (:goal (and (in ball6 roomb)
               (in ball5 roomb)
               (in ball4 roomb)
               (in ball3 roomb)
               (in ball2 roomb)
               (in ball1 roomb))))
