(define (problem strips-gripper-x-1)
   (:domain gripper-strips)
   (:objects rooma roomb ball4 ball3 ball2 ball1 left right - object)
   (:init (room rooma)
          (room roomb)
          (ball ball4)
          (ball ball3)
          (ball ball2)
          (ball ball1)
          (at-robby rooma)
          (free left)
          (free right)
          (in ball4 rooma)
          (in ball3 rooma)
          (in ball2 rooma)
          (in ball1 rooma)
          (gripper left)
          (gripper right))
   (:goal (and (in ball4 roomb)
               (in ball3 roomb)
               (in ball2 roomb)
               (in ball1 roomb))))
