(define (problem strips-gripper-x-5)
   (:domain gripper-strips)
   (:objects rooma roomb ball12 ball11 ball10 ball9 ball8 ball7 ball6
             ball5 ball4 ball3 ball2 ball1 left right - object)
   (:init (room rooma)
          (room roomb)
          (ball ball12)
          (ball ball11)
          (ball ball10)
          (ball ball9)
          (ball ball8)
          (ball ball7)
          (ball ball6)
          (ball ball5)
          (ball ball4)
          (ball ball3)
          (ball ball2)
          (ball ball1)
          (at-robby rooma)
          (free left)
          (free right)
          (in ball12 rooma)
          (in ball11 rooma)
          (in ball10 rooma)
          (in ball9 rooma)
          (in ball8 rooma)
          (in ball7 rooma)
          (in ball6 rooma)
          (in ball5 rooma)
          (in ball4 rooma)
          (in ball3 rooma)
          (in ball2 rooma)
          (in ball1 rooma)
          (gripper left)
          (gripper right))
   (:goal (and (in ball12 roomb)
               (in ball11 roomb)
               (in ball10 roomb)
               (in ball9 roomb)
               (in ball8 roomb)
               (in ball7 roomb)
               (in ball6 roomb)
               (in ball5 roomb)
               (in ball4 roomb)
               (in ball3 roomb)
               (in ball2 roomb)
               (in ball1 roomb))))
